#!/usr/bin/env python2.7

# Filter converts time_t values at beginning of lines to
# YYYY-HH-MM HH:MM formatted representation.

import sys
import re
import datetime

def to_date(match):
    return datetime.datetime.fromtimestamp(int(match.group(1))).strftime("%Y-%m-%d %H:%M")

for line in sys.stdin:
    print re.sub("(\d{10})", to_date, line),

